name = "kit_schema"
description = "Intermediate tree representation of Kit database specification"
version = "0.1.0-dev"
licenses= "GPL-3.0-or-later"

authors = ["Fraser Wilson"]
maintainers = ["Fraser Wilson <fraser@thewhitelion.eu>"]
maintainers-logins = ["blancolioni"]

tags = ["utility", "database", "compiler"]
website = "https://github.com/blancolioni/kit_schema"

[[depends-on]]
wl_lib = "~0.1.0-dev"
[[depends-on]]
marlowe = "~0.1.0-dev"
[[depends-on]]
kit_base = "~0.1.0-dev"
[[depends-on]]
syn = "~0.1.0-dev"

